var annotated_dup =
[
    [ "AlternativesGenerator", "class_alternatives_generator.html", "class_alternatives_generator" ],
    [ "AppController", "class_app_controller.html", "class_app_controller" ],
    [ "FractController", "class_fract_controller.html", "class_fract_controller" ],
    [ "FractControllerAcuity", "class_fract_controller_acuity.html", "class_fract_controller_acuity" ],
    [ "FractControllerAcuityC", "class_fract_controller_acuity_c.html", "class_fract_controller_acuity_c" ],
    [ "FractControllerAcuityE", "class_fract_controller_acuity_e.html", "class_fract_controller_acuity_e" ],
    [ "FractControllerAcuityL", "class_fract_controller_acuity_l.html", "class_fract_controller_acuity_l" ],
    [ "FractControllerAcuityTAO", "class_fract_controller_acuity_t_a_o.html", "class_fract_controller_acuity_t_a_o" ],
    [ "FractControllerAcuityVernier", "class_fract_controller_acuity_vernier.html", "class_fract_controller_acuity_vernier" ],
    [ "FractControllerContrast", "class_fract_controller_contrast.html", "class_fract_controller_contrast" ],
    [ "FractControllerContrastC", "class_fract_controller_contrast_c.html", "class_fract_controller_contrast_c" ],
    [ "FractControllerContrastE", "class_fract_controller_contrast_e.html", "class_fract_controller_contrast_e" ],
    [ "FractControllerContrastLett", "class_fract_controller_contrast_lett.html", "class_fract_controller_contrast_lett" ],
    [ "FractView", "class_fract_view.html", "class_fract_view" ],
    [ "GammaView", "class_gamma_view.html", "class_gamma_view" ],
    [ "HierarchyController", "class_hierarchy_controller.html", "class_hierarchy_controller" ],
    [ "MDBdispersionEstimation", "class_m_d_bdispersion_estimation.html", "class_m_d_bdispersion_estimation" ],
    [ "mdbSimplestatistics", "classmdb_simplestatistics.html", "classmdb_simplestatistics" ],
    [ "Misc", "class_misc.html", null ],
    [ "Optotypes", "class_optotypes.html", "class_optotypes" ],
    [ "RewardsController", "class_rewards_controller.html", "class_rewards_controller" ],
    [ "Settings", "class_settings.html", null ],
    [ "Sound", "class_sound.html", "class_sound" ],
    [ "TAOController", "class_t_a_o_controller.html", "class_t_a_o_controller" ],
    [ "Thresholder", "class_thresholder.html", "class_thresholder" ],
    [ "ThresholderPest", "class_thresholder_pest.html", "class_thresholder_pest" ],
    [ "TrialHistoryController", "class_trial_history_controller.html", "class_trial_history_controller" ]
];